PartiuFesta/Models/Festa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PartiuFesta.Models
{
    public class Festa : Entity
    {
        [DisplayName("Nome da festa")]
        [Required(ErrorMessage = "O campo Nome da festa é Obrigatorio")]
        [StringLength(200, ErrorMessage = " O campo prescisa ter entre 1 e 200 caracter", MinimumLength = 1)]
        public string Nome_Da_Festa { get; set; }

        [DisplayName("Nome do anfitrião")]
        [Required(ErrorMessage = "O campo Nome do anfitrião é Obrigatorio")]
        [StringLength(200, ErrorMessage = " O campo prescisa ter entre 1 e 200 caracter", MinimumLength = 1)]
        public string Anfitriao { get; set; }

        [DisplayName("Tipo da Festa")]
        public TipoFesta TipoFesta { get; set; }

        [Required(ErrorMessage = "O campo Cidade é Obrigatorio")]
        [StringLength(200, ErrorMessage = " O campo prescisa ter entre 1 e 200 caracter", MinimumLength = 1)]
        public string Cidade { get; set; }

        [Required(ErrorMessage = "O campo Bairro é Obrigatorio")]
        [StringLength(200, ErrorMessage = " O campo prescisa ter entre 1 e 200 caracter", MinimumLength = 1)]
        public string Bairro { get; set; }

        [Required(ErrorMessage = "O campo Rua é Obrigatorio")]
        [StringLength(200, ErrorMessage = " O campo prescisa ter entre 1 e 200 caracter", MinimumLength = 1)]
        public string Rua { get; set; }

        [Required(ErrorMessage = "O campo Numero é Obrigatorio")]
        [StringLength(5, ErrorMessage = " O campo prescisa ter entre 1 e 5 caracter", MinimumLength = 1)]
        public string Numero { get; set; }

        [DisplayName("Data da Festa")]
        public DateTime DataDaFesta { get; set; }

        [DisplayName("Link do Google Mapas")]
        public string Link_Do_Google_Maps { get; set; }

        /*EF RELACAO*/

        public IEnumerable<Participante> Participantes { get; set; }
    }
}

PartiuFesta/Controllers/FestasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PartiuFesta.Data.Context;
using PartiuFesta.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PartiuFesta.Controllers
{
    public class FestasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FestasController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Festas.ToListAsync());
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var festa = await _context.Festas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (festa == null)
            {
                return NotFound();
            }

            return View(festa);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome_Da_Festa,Anfitriao,TipoFesta,Cidade,Bairro,Rua,Numero,DataDaFesta,Link_Do_Google_Maps,Id")] Festa festa)
        {
            if (ModelState.IsValid)
            {
                festa.Id = Guid.NewGuid();
                _context.Add(festa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(festa);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var festa = await _context.Festas.FindAsync(id);
            if (festa == null)
            {
                return NotFound();
            }
            return View(festa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Nome_Da_Festa,Anfitriao,TipoFesta,Cidade,Bairro,Rua,Numero,DataDaFesta,Link_Do_Google_Maps,Id")] Festa festa)
        {
            if (id != festa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(festa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FestaExists(festa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(festa);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var festa = await _context.Festas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (festa == null)
            {
                return NotFound();
            }

            return View(festa);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var festa = await _context.Festas.FindAsync(id);
            _context.Festas.Remove(festa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FestaExists(Guid id)
        {
            return _context.Festas.Any(e => e.Id == id);
        }
    }
}

PartiuFesta/Controllers/ParticipantesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PartiuFesta.Data.Context;
using PartiuFesta.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PartiuFesta.Controllers
{
    public class ParticipantesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ParticipantesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Participantes.Include(p => p.Festa);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participante = await _context.Participantes
                .Include(p => p.Festa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participante == null)
            {
                return NotFound();
            }

            return View(participante);
        }

        public IActionResult Create()
        {
            ViewData["FestaId"] = new SelectList(_context.Festas, "Id", "Anfitriao");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Participante participante)
        {
            if (ModelState.IsValid)
            {
                participante.Id = Guid.NewGuid();
                _context.Add(participante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FestaId"] = new SelectList(_context.Festas, "Id", "Anfitriao", participante.FestaId);
            return View(participante);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participante = await _context.Participantes.FindAsync(id);
            if (participante == null)
            {
                return NotFound();
            }
            ViewData["FestaId"] = new SelectList(_context.Festas, "Id", "Anfitriao", participante.FestaId);
            return View(participante);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Participante participante)
        {
            if (id != participante.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(participante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParticipanteExists(participante.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FestaId"] = new SelectList(_context.Festas, "Id", "Anfitriao", participante.FestaId);
            return View(participante);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participante = await _context.Participantes
                .Include(p => p.Festa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participante == null)
            {
                return NotFound();
            }

            return View(participante);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var participante = await _context.Participantes.FindAsync(id);
            _context.Participantes.Remove(participante);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ParticipanteExists(Guid id)
        {
            return _context.Participantes.Any(e => e.Id == id);
        }
    }
}

PartiuFesta/Views/Festas/Create.cshtml
@model PartiuFesta.Models.Festa

@{
    ViewData["Title"] = "Nova Festa";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome_Da_Festa" class="control-label"></label>
                <input asp-for="Nome_Da_Festa" class="form-control" />
                <span asp-validation-for="Nome_Da_Festa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anfitriao" class="control-label"></label>
                <input asp-for="Anfitriao" class="form-control" />
                <span asp-validation-for="Anfitriao" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bairro" class="control-label"></label>
                <input asp-for="Bairro" class="form-control" />
                <span asp-validation-for="Bairro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rua" class="control-label"></label>
                <input asp-for="Rua" class="form-control" />
                <span asp-validation-for="Rua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDaFesta" class="control-label"></label>
                <input asp-for="DataDaFesta" class="form-control" />
                <span asp-validation-for="DataDaFesta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link_Do_Google_Maps" class="control-label"></label>
                <input asp-for="Link_Do_Google_Maps" class="form-control" />
                <span asp-validation-for="Link_Do_Google_Maps" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TipoFesta" class="control-label"></label><br />
                <input type="radio" name="TipoFesta" value="4" checked />Casual<br />
                <input type="radio" name="TipoFesta" value="1" />Infantil <br />
                <input type="radio" name="TipoFesta" value="2" />Aniversario <br />
                <input type="radio" name="TipoFesta" value="3" />violão<br />
                <input type="radio" name="TipoFesta" value="5" />HardCore<br />
                <input type="radio" name="TipoFesta" value="6" />Acampamento<br />

            </div>

            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-info" />|
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

PartiuFesta/Views/Festas/Delete.cshtml
@model PartiuFesta.Models.Festa


@{
    ViewData["Title"] = "Delete";
}

<h1>Excluir</h1>

<h3>Deseja realmente excluir ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome_Da_Festa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome_Da_Festa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Anfitriao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Anfitriao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoFesta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoFesta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bairro)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rua)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rua)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataDaFesta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataDaFesta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Link_Do_Google_Maps)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Link_Do_Google_Maps)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a class="btn btn-info" asp-action="Index">Voltar</a>
    </form>
</div>

PartiuFesta/Views/Festas/Details.cshtml
@model PartiuFesta.Models.Festa

@{
    ViewData["Title"] = "Detalhes";
}

<h1>@ViewData["Title"]</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome_Da_Festa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome_Da_Festa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Anfitriao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Anfitriao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoFesta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoFesta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bairro)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rua)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rua)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataDaFesta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataDaFesta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Link_Do_Google_Maps)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Link_Do_Google_Maps)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-info" asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model.Id">Excluir</a>|
    <a class="btn btn-info" href=@Html.DisplayFor(model => model.Link_Do_Google_Maps)>Google Maps da festa</a>|
    <a class="btn btn-info" asp-action="Index">Voltar</a>|

</div>

PartiuFesta/Views/Festas/Edit.cshtml
@model PartiuFesta.Models.Festa

@{
    ViewData["Title"] = "Editar Festa";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome_Da_Festa" class="control-label"></label>
                <input asp-for="Nome_Da_Festa" class="form-control" />
                <span asp-validation-for="Nome_Da_Festa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anfitriao" class="control-label"></label>
                <input asp-for="Anfitriao" class="form-control" />
                <span asp-validation-for="Anfitriao" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bairro" class="control-label"></label>
                <input asp-for="Bairro" class="form-control" />
                <span asp-validation-for="Bairro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rua" class="control-label"></label>
                <input asp-for="Rua" class="form-control" />
                <span asp-validation-for="Rua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDaFesta" class="control-label"></label>
                <input asp-for="DataDaFesta" class="form-control" />
                <span asp-validation-for="DataDaFesta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link_Do_Google_Maps" class="control-label"></label>
                <input asp-for="Link_Do_Google_Maps" class="form-control" />
                <span asp-validation-for="Link_Do_Google_Maps" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TipoFesta" class="control-label"></label><br />
                <input type="radio" name="TipoFesta" value="4" checked />Casual<br />
                <input type="radio" name="TipoFesta" value="1" />Infantil <br />
                <input type="radio" name="TipoFesta" value="2" />Aniversario <br />
                <input type="radio" name="TipoFesta" value="3" />violão<br />
                <input type="radio" name="TipoFesta" value="5" />HardCore<br />
                <input type="radio" name="TipoFesta" value="6" />Swing<br />

            </div>


            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />|
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

PartiuFesta/Views/Festas/Index.cshtml
@model IEnumerable<PartiuFesta.Models.Festa>

@{
    ViewData["Title"] = "Lista de Festas Publicas";
}

<h1>@ViewData["Title"]</h1>


<p>
    <a class="btn btn-outline-success" asp-action="Create">Faser Nova Festa</a>

</p>
<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome_Da_Festa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anfitriao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoFesta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cidade)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.DataDaFesta)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome_Da_Festa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Anfitriao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoFesta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cidade)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.DataDaFesta)
                </td>
               
                <td>

                    <a asp-action="Details" class="btn btn-info" asp-route-id="@item.Id">Detalhes</a>

                    <a class="btn btn-info" asp-controller="Participantes" asp-action="Index">Participar</a>

                </td>
            </tr>
        }
    </tbody>
</table>