PartiuFesta/Controllers/FestasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PartiuFesta.Data.Context;
using PartiuFesta.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PartiuFesta.Controllers
{
    public class FestasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FestasController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Festas.ToListAsync());
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var festa = await _context.Festas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (festa == null)
            {
                return NotFound();
            }

            return View(festa);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome_Da_Festa,Anfitriao,TipoFesta,Cidade,Bairro,Rua,Numero,DataDaFesta,Link_Do_Google_Maps,Id")] Festa festa)
        {
            if (ModelState.IsValid)
            {
                festa.Id = Guid.NewGuid();
                _context.Add(festa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(festa);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var festa = await _context.Festas.FindAsync(id);
            if (festa == null)
            {
                return NotFound();
            }
            return View(festa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Nome_Da_Festa,Anfitriao,TipoFesta,Cidade,Bairro,Rua,Numero,DataDaFesta,Link_Do_Google_Maps,Id")] Festa festa)
        {
            if (id != festa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(festa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FestaExists(festa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(festa);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var festa = await _context.Festas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (festa == null)
            {
                return NotFound();
            }

            return View(festa);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var festa = await _context.Festas.FindAsync(id);
            _context.Festas.Remove(festa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FestaExists(Guid id)
        {
            return _context.Festas.Any(e => e.Id == id);
        }
    }
}

PartiuFesta/Controllers/FestasPrivadasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PartiuFesta.Data.Context;
using PartiuFesta.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PartiuFesta.Controllers
{
    public class FestasPrivadasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FestasPrivadasController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.FestasPrivadas.ToListAsync());
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var festaPrivada = await _context.FestasPrivadas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (festaPrivada == null)
            {
                return NotFound();
            }

            return View(festaPrivada);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FestaPrivada festaPrivada)
        {
            if (ModelState.IsValid)
            {
                festaPrivada.Id = Guid.NewGuid();
                _context.Add(festaPrivada);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(festaPrivada);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var festaPrivada = await _context.FestasPrivadas.FindAsync(id);
            if (festaPrivada == null)
            {
                return NotFound();
            }
            return View(festaPrivada);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, FestaPrivada festaPrivada)
        {
            if (id != festaPrivada.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(festaPrivada);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FestaPrivadaExists(festaPrivada.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(festaPrivada);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var festaPrivada = await _context.FestasPrivadas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (festaPrivada == null)
            {
                return NotFound();
            }

            return View(festaPrivada);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var festaPrivada = await _context.FestasPrivadas.FindAsync(id);
            _context.FestasPrivadas.Remove(festaPrivada);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FestaPrivadaExists(Guid id)
        {
            return _context.FestasPrivadas.Any(e => e.Id == id);
        }
    }
}

PartiuFesta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>

   
    

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] -Fazendo festa</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: Lavender; ">


  



        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fazendo Festa</a>>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"></a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-outline-success" asp-area="" asp-controller="Festas" asp-action="Index">Festas Publicas</a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-outline-success" asp-area="" asp-controller="FestasPrivadas" asp-action="Index">Festas Privadas</a>
                            </li>




                        </ul>
                        <partial name="_LoginPartial" />
                    </div>


                </div>
            </nav>



        </header>





        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Partiu Festa - <a asp-area="" asp-controller="Home" asp-action="Privacy">um pouco sobre nós</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>